name: Build SunamoStringSplit

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoStringSplit
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringSplit/SunamoStringSplit.csproj

    - name: Build
      run: dotnet build SunamoStringSplit/SunamoStringSplit.csproj --configuration Release --no-restore

  test:
    name: Test SunamoStringSplit.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringSplit.Tests/SunamoStringSplit.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoStringSplit.Tests/SunamoStringSplit.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoStringSplit.Tests/SunamoStringSplit.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
